### ISSUE TITLE
BigText taking ~5sec to apply after full site loads, Wordpress

### ISSUE THREAD

**Issue by trishss** [zachleat/BigText#110]
I have used bigtext.js previously and in a similar way with a Concrete5 site and had no load time issues with, and am trying the same thing again on a wordpress site, and it is functioning as it should, however it takes about ~5sec to apply its effect even though nothing else on the site seems to take as long to load.

I minified the .js file and was working locally with MAMP and had this problem even then, so I do not think it is related to internet speed. I've tried it on multiple themes and it seems to be happening regardless.

The effect can be seen on [my website](http://trishss.com) when hovering over a thumbnail image. If you hover over right when the page loads, the text appears very small before the effect applies, which causes it to fit each line to the width of the thumbnail.

**Comment by zachleat** [comment]
Did you figure it out?

**Comment by trishss** [comment]
It actually was due to my theme. I tried it with another and I didn't have the problem with slow load but I did have other issues with it applying erratically to only some elements on some page loads.
