### ISSUE TITLE
The latest release is no longer compatible with jQuery 3

### ISSUE THREAD

**Issue by smohadjer** [zachleat/BigText#135]
After upgrading to new version (1.0.1) I noticed that jquery migrate plugin throws warnings because of using "bind" and "unbind" in following line:

`$(window).unbind(eventName).bind(eventName, function() {`

Bind/unbind are deprecated in jQuery 3. Use on/off to attach/detach event listeners.

**Comment by deep-spaced** [comment]
Just made a PR for this. Thank you!

**Comment by zachleat** [comment]
Fixed by #136. Will be included with 1.0.2

**Comment by deep-spaced** [comment]
Thank you!

**Comment by smohadjer** [comment]
Thanks guys.
