### ISSUE TITLE
BigText not working on iPhone

### ISSUE THREAD

**Issue by RBUSA** [zachleat/BigText#18]
Hi all,

http://bootcoffee.com/about/

I'm working on a site using BigText and I can't seem to get it to load on an iPhone. Has anyone else had this issue?

When testing using a user agent switch in Firefox, it works as it should. However on an iPhone, it doesn't, which makes it hard to test.

Thought I'd check here if someone had some advice for me.

Thanks,
Rick.

**Comment by zachleat** [comment]
0.1.7 on the demo http://zachleat.github.io/BigText/demo/simpleDemo.html seems to be working fine on iOS 8. Please reopen if you have additional issues.
