### ISSUE TITLE
doesn't play nicely with jQuery Cycle

### ISSUE THREAD

**Issue by safeasmilk** [zachleat/BigText#21]
Hi - thanks for the plugin - I'm trying to cycle through different divs containing text using the famous jQuery Cycle but if you resize your browser on desktop - or change orientation on mobile it breaks

could this be to do with the way Cycle 'hides' the next slides in the cycle?

here's a test http://safeasmilk.org/wordthing/things-test/

**Comment by zachleat** [comment]
Closing as inactive.
