### ISSUE TITLE
TypeError: Argument 1 of Window.getComputedStyle is not an object

### ISSUE THREAD

**Issue by multiformeingegno** [zachleat/BigText#61]
Here's what I get:
![bigtext](https://cloud.githubusercontent.com/assets/4039005/4100452/747aa918-3098-11e4-8b59-f3202ff0b67b.png)

jQuery 2.1.1

**Comment by hynese** [comment]
I can confirm this. The plugin is unusable on Firefox/Yosemite.

Here's the fix:
```
          var computedStyle="";
          try{
          var test = $('<div/>').css({
              position: 'absolute',
              'font-size': '14.1px'
            }).appendTo(document.body).get(0),
            computedStyle = window.getComputedStyle( test, null );
          }catch(e){
            //do nothing
          }
          return computedStyle ? computedStyle.getPropertyValue( 'font-size' ) === '14px' : true;
```

**Comment by zachleat** [comment]
The plugin needs to run either on `DOMContentLoaded` or you can place it inside a `requestAnimationFrame` callback. I’ll probably build this into the plugin eventually so that it handles it transparently.

**Comment by fezzik1620** [comment]
I can confirm seeing this on Chrome beta 41.0.2272.74.  An associate of mine on the same network, loading the same internal page not using the beta release of Chrome is not seeing this behavior.

**Comment by ashinzekene** [comment]
Window.getComputedStyle does not work when you use  document.querySelector. it works when u use getElementById

**Comment by muskanbardia1** [comment]
how to resolve this error in react?

**Comment by muskanbardia1** [comment]
Window.getComputedStyle: Argument 1 is not an object.
